### PR TITLE
feat: add app config

### PR DESCRIPTION
**Pull request by badsyntax**
I have a requirement to set app config which will change with each deploy (i need to set my app version based on the release tag).

### CODE REVIEW

**Comment by josegonzalez** [comment]
I don't really want to overcomplicate this because folks will complain about newlines, base64 support, or even other dokku commands.

Can you tell me a bit more about your specific use case, and maybe why the GIT_REV isn't useful enough?

**Comment by badsyntax** [comment]
I had similar concerns tbh. 

My use case is I collect app metrics and I need an app version that is "human readable". I set my app version using my release tag (eg 0.0.1, 0.0.2 etc) allowing me to analyse the metrics easier. Using the git sha would also not work with the hacky approach outlined in https://github.com/dokku/github-action/pull/5  

Screenshot 2021-01-07 at 12 16 26

**Comment by badsyntax** [comment]
Another possible approach would be opening up the ssh command in the GitHub to allow us to run arbitrary dokku commands

**Comment by badsyntax** [comment]
I could potentially work around this as part of the docker build phase. I can save the version to disk and read that at runtime.

**Comment by josegonzalez** [comment]
Yeah I think if you're pushing an image, thats probably the way to go in your case. I think the use case is reasonable, but my concern is that this opens up the image to structured ways of performing any arbitrary command, which is something I'd like to avoid for my own sanity.

**Comment by badsyntax** [comment]
Understood, and agree 👍  I'll close the PR's. Thanks.

**Pull request closed without merging**
