### PR TITLE
Added git:from-image to commands

### PR DESCRIPTION
**Pull request by aaronjdale**
Added git:from-image to the commands which allows the direct deployment of an existing docker image.

Env variables required:
COMMAND: git:from-image
IMAGE_NAME: some-docker/image:here

### CODE REVIEW

**Comment by josegonzalez** [comment]
Can you add documentation to the readme for this as well?

**Comment by aaronjdale** [comment]
Sure. Not sure where, or what format, to put it since no other `COMMAND` appears to be documented. I dove into the actual script to find them.

Perhaps an "examples" section?

**Comment by josegonzalez** [comment]
- We need a new entry for `IMAGE_NAME` [here](https://github.com/dokku/ci-docker-image#configuration).
- Probably makes sense to add a new section for each of the commands?
- I _am_ concerned IMAGE_NAME will be injected by upstream CI systems. Would you mind checking each of the ones we list in our readme to verify we aren't clashing with something in use?

**Comment by aaronjdale** [comment]
I agree that a section detailing each command would be helpful. 

I added `IMAGE_NAME` to the env variables section.

And finally I went through all the docs regarding the predefined env variables for all the support CI pipelines. There is no conflict, however, that did lead me to suggest possibly prefixing the env variables in this image so that the chances of an unintentional collision is greatly reduced. That's a topic for another day though.

**Comment by cerino-ligutom** [comment]
Can we have this merged?

**Comment by josegonzalez** [comment]
Yeah I'll have some time to look at this (and others) this weekend. Anything related to deploying an app (whether thats from an image, dockerfile, or source) seems like good to support.

**Comment by josegonzalez** [comment]
I'm revisiting this MR because the repo has changed slightly, but I'd like to thank @aaronjdale for submitting the MR in the first place!

**Pull request closed without merging**
